name: Security Update Tests

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - package.json
      - package-lock.json

jobs:
  test:
    if: contains(github.head_ref, 'dependabot')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run build
        run: npm run build
